<?php
return
array(
    array(
        'key' => 'field_65cc8de858ea0',
        'label' => 'Company website',
        'name' => 'company_website',
        'aria-label' => '',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
    ),
    array(
        'key' => 'field_65cc8e0c58ea1',
        'label' => 'Company Twitter',
        'name' => 'company_twitter',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'placeholder' => '@twi',
        'prepend' => '',
        'append' => '',
    ),
    array(
        'key' => 'field_65cc8e1458ea2',
        'label' => 'Company Video',
        'name' => 'company_video',
        'aria-label' => '',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => '.mp4,.mov',
    ),
    array(
        'key' => 'field_65cc8e1e58ea3',
        'label' => 'Company icon',
        'name' => 'company_logo',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
    ),
    array(
        'key' => 'field_65cc8f26a3939',
        'label' => 'Company Users',
        'name' => 'company_users',
        'aria-label' => '',
        'type' => 'user',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'role' => '',
        'return_format' => 'array',
        'multiple' => 1,
        'allow_null' => 0,
        'bidirectional' => 0,
        'bidirectional_target' => array(),
    ),
);